### ISSUE TITLE
ASSALTO

### ISSUE THREAD

**Issue by tomascarruco** [G4ma/PP1#1]
# YOUR CODE ALL IN THE BAG, NOW!!!!!!!!
![THE PRESSURE](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.explicit.bing.net%2Fth%3Fid%3DOIP.jEu5WboAdEk-e8dfkE2_bAAAAA%26pid%3DApi&f=1)
# ALL THE CODE NOW!!!!!
![THE BAG](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.tennisplaza.com%2Fprodimages%2Falt_images%2Flarge%2F40L20BAG20_2.jpg&f=1&nofb=1)

**Comment by 2mas1belino** [comment]
não dou
